### ISSUE TITLE
Input Features for Chameleon and Squirrel

### ISSUE THREAD

**Issue by YiteWang** [LUMIA-Group/OrderedGNN#1]
Thank you for the amazing work! I am new to GNN and I am a little confused why you change the input feature of `Chameleon` and `Squirrel` to  one hot encoding in https://github.com/LUMIA-Group/OrderedGNN/blob/main/task_node.py#L23:

`data.x = torch.eye(data.x.shape[0]) `

Thank you so much!

**Comment by yunchong-song** [comment]
Thank you for your interest! We use the setting described in Section 4.3 of [1] for `Chameleon` and `Squirrel`. In practice, we have found that the node features in these two datasets are less informative and can potentially mislead our gating module, which is purely data-driven. Therefore, we replace the input feature with one-hot encoding so that GNN mainly relies on the graph structure. You can refer to Table 4 and 5 in [1] to check the performance of the baseline models under this setting.

[1] Graph Neural Networks with Heterophily, AAAI 2021

**Comment by YiteWang** [comment]
Thank you for the explanation!
